insert into movie(id,MOVIE_NAME) values('1','TestMovie_1');
insert into movie(id,MOVIE_NAME) values('2','TestMovie_2');
insert into movie(id,MOVIE_NAME) values('3','TestMovie_3');
insert into movie(id,MOVIE_NAME) values('4','TestMovie_4');
insert into movie(id,MOVIE_NAME) values('5','TestMovie_5');
insert into movie(id,MOVIE_NAME) values('6','TestMovie_6');
insert into movie(id,MOVIE_NAME) values('7','TestMovie_7');
insert into movie(id,MOVIE_NAME) values('8','TestMovie_8');
insert into movie(id,MOVIE_NAME) values('9','TestMovie_9');